export const COUNTRY_CODES = [
  { code: '+93', flag: '🇦🇫', name: 'AF', fullName: 'Afghanistan' },
  { code: '+355', flag: '🇦🇱', name: 'AL', fullName: 'Albania' },
  { code: '+213', flag: '🇩🇿', name: 'DZ', fullName: 'Algeria' },
  { code: '+376', flag: '🇦🇩', name: 'AD', fullName: 'Andorra' },
  { code: '+244', flag: '🇦🇴', name: 'AO', fullName: 'Angola' },
  { code: '+1268', flag: '🇦🇬', name: 'AG', fullName: 'Antigua and Barbuda' },
  { code: '+54', flag: '🇦🇷', name: 'AR', fullName: 'Argentina' },
  { code: '+374', flag: '🇦🇲', name: 'AM', fullName: 'Armenia' },
  { code: '+61', flag: '🇦🇺', name: 'AU', fullName: 'Australia' },
  { code: '+43', flag: '🇦🇹', name: 'AT', fullName: 'Austria' },
  { code: '+994', flag: '🇦🇿', name: 'AZ', fullName: 'Azerbaijan' },
  { code: '+1242', flag: '🇧🇸', name: 'BS', fullName: 'Bahamas' },
  { code: '+973', flag: '🇧🇭', name: 'BH', fullName: 'Bahrain' },
  { code: '+880', flag: '🇧🇩', name: 'BD', fullName: 'Bangladesh' },
  { code: '+1246', flag: '🇧🇧', name: 'BB', fullName: 'Barbados' },
  { code: '+375', flag: '🇧🇾', name: 'BY', fullName: 'Belarus' },
  { code: '+32', flag: '🇧🇪', name: 'BE', fullName: 'Belgium' },
  { code: '+501', flag: '🇧🇿', name: 'BZ', fullName: 'Belize' },
  { code: '+229', flag: '🇧🇯', name: 'BJ', fullName: 'Benin' },
  { code: '+975', flag: '🇧🇹', name: 'BT', fullName: 'Bhutan' },
  { code: '+591', flag: '🇧🇴', name: 'BO', fullName: 'Bolivia' },
  { code: '+387', flag: '🇧🇦', name: 'BA', fullName: 'Bosnia and Herzegovina' },
  { code: '+267', flag: '🇧🇼', name: 'BW', fullName: 'Botswana' },
  { code: '+55', flag: '🇧🇷', name: 'BR', fullName: 'Brazil' },
  { code: '+673', flag: '🇧🇳', name: 'BN', fullName: 'Brunei' },
  { code: '+359', flag: '🇧🇬', name: 'BG', fullName: 'Bulgaria' },
  { code: '+226', flag: '🇧🇫', name: 'BF', fullName: 'Burkina Faso' },
  { code: '+257', flag: '🇧🇮', name: 'BI', fullName: 'Burundi' },
  { code: '+238', flag: '🇨🇻', name: 'CV', fullName: 'Cabo Verde' },
  { code: '+855', flag: '🇰🇭', name: 'KH', fullName: 'Cambodia' },
  { code: '+237', flag: '🇨🇲', name: 'CM', fullName: 'Cameroon' },
  { code: '+1', flag: '🇨🇦', name: 'CA', fullName: 'Canada' },
  { code: '+236', flag: '🇨🇫', name: 'CF', fullName: 'Central African Republic' },
  { code: '+235', flag: '🇹🇩', name: 'TD', fullName: 'Chad' },
  { code: '+56', flag: '🇨🇱', name: 'CL', fullName: 'Chile' },
  { code: '+86', flag: '🇨🇳', name: 'CN', fullName: 'China' },
  { code: '+57', flag: '🇨🇴', name: 'CO', fullName: 'Colombia' },
  { code: '+269', flag: '🇰🇲', name: 'KM', fullName: 'Comoros' },
  { code: '+242', flag: '🇨🇬', name: 'CG', fullName: 'Congo' },
  { code: '+243', flag: '🇨🇩', name: 'CD', fullName: 'Congo (DRC)' },
  { code: '+506', flag: '🇨🇷', name: 'CR', fullName: 'Costa Rica' },
  { code: '+225', flag: '🇨🇮', name: 'CI', fullName: 'Ivory Coast' },
  { code: '+385', flag: '🇭🇷', name: 'HR', fullName: 'Croatia' },
  { code: '+53', flag: '🇨🇺', name: 'CU', fullName: 'Cuba' },
  { code: '+357', flag: '🇨🇾', name: 'CY', fullName: 'Cyprus' },
  { code: '+420', flag: '🇨🇿', name: 'CZ', fullName: 'Czech Republic' },
  { code: '+45', flag: '🇩🇰', name: 'DK', fullName: 'Denmark' },
  { code: '+253', flag: '🇩🇯', name: 'DJ', fullName: 'Djibouti' },
  { code: '+1767', flag: '🇩🇲', name: 'DM', fullName: 'Dominica' },
  { code: '+1809', flag: '🇩🇴', name: 'DO', fullName: 'Dominican Republic' },
  { code: '+593', flag: '🇪🇨', name: 'EC', fullName: 'Ecuador' },
  { code: '+20', flag: '🇪🇬', name: 'EG', fullName: 'Egypt' },
  { code: '+503', flag: '🇸🇻', name: 'SV', fullName: 'El Salvador' },
  { code: '+240', flag: '🇬🇶', name: 'GQ', fullName: 'Equatorial Guinea' },
  { code: '+291', flag: '🇪🇷', name: 'ER', fullName: 'Eritrea' },
  { code: '+372', flag: '🇪🇪', name: 'EE', fullName: 'Estonia' },
  { code: '+268', flag: '🇸🇿', name: 'SZ', fullName: 'Eswatini' },
  { code: '+251', flag: '🇪🇹', name: 'ET', fullName: 'Ethiopia' },
  { code: '+679', flag: '🇫🇯', name: 'FJ', fullName: 'Fiji' },
  { code: '+358', flag: '🇫🇮', name: 'FI', fullName: 'Finland' },
  { code: '+33', flag: '🇫🇷', name: 'FR', fullName: 'France' },
  { code: '+241', flag: '🇬🇦', name: 'GA', fullName: 'Gabon' },
  { code: '+220', flag: '🇬🇲', name: 'GM', fullName: 'Gambia' },
  { code: '+995', flag: '🇬🇪', name: 'GE', fullName: 'Georgia' },
  { code: '+49', flag: '🇩🇪', name: 'DE', fullName: 'Germany' },
  { code: '+233', flag: '🇬🇭', name: 'GH', fullName: 'Ghana' },
  { code: '+30', flag: '🇬🇷', name: 'GR', fullName: 'Greece' },
  { code: '+1473', flag: '🇬🇩', name: 'GD', fullName: 'Grenada' },
  { code: '+502', flag: '🇬🇹', name: 'GT', fullName: 'Guatemala' },
  { code: '+224', flag: '🇬🇳', name: 'GN', fullName: 'Guinea' },
  { code: '+245', flag: '🇬🇼', name: 'GW', fullName: 'Guinea-Bissau' },
  { code: '+592', flag: '🇬🇾', name: 'GY', fullName: 'Guyana' },
  { code: '+509', flag: '🇭🇹', name: 'HT', fullName: 'Haiti' },
  { code: '+504', flag: '🇭🇳', name: 'HN', fullName: 'Honduras' },
  { code: '+852', flag: '🇭🇰', name: 'HK', fullName: 'Hong Kong' },
  { code: '+36', flag: '🇭🇺', name: 'HU', fullName: 'Hungary' },
  { code: '+354', flag: '🇮🇸', name: 'IS', fullName: 'Iceland' },
  { code: '+91', flag: '🇮🇳', name: 'IN', fullName: 'India' },
  { code: '+62', flag: '🇮🇩', name: 'ID', fullName: 'Indonesia' },
  { code: '+98', flag: '🇮🇷', name: 'IR', fullName: 'Iran' },
  { code: '+964', flag: '🇮🇶', name: 'IQ', fullName: 'Iraq' },
  { code: '+353', flag: '🇮🇪', name: 'IE', fullName: 'Ireland' },
  { code: '+972', flag: '🇮🇱', name: 'IL', fullName: 'Israel' },
  { code: '+39', flag: '🇮🇹', name: 'IT', fullName: 'Italy' },
  { code: '+1876', flag: '🇯🇲', name: 'JM', fullName: 'Jamaica' },
  { code: '+81', flag: '🇯🇵', name: 'JP', fullName: 'Japan' },
  { code: '+962', flag: '🇯🇴', name: 'JO', fullName: 'Jordan' },
  { code: '+7', flag: '🇰🇿', name: 'KZ', fullName: 'Kazakhstan' },
  { code: '+254', flag: '🇰🇪', name: 'KE', fullName: 'Kenya' },
  { code: '+686', flag: '🇰🇮', name: 'KI', fullName: 'Kiribati' },
  { code: '+965', flag: '🇰🇼', name: 'KW', fullName: 'Kuwait' },
  { code: '+996', flag: '🇰🇬', name: 'KG', fullName: 'Kyrgyzstan' },
  { code: '+856', flag: '🇱🇦', name: 'LA', fullName: 'Laos' },
  { code: '+371', flag: '🇱🇻', name: 'LV', fullName: 'Latvia' },
  { code: '+961', flag: '🇱🇧', name: 'LB', fullName: 'Lebanon' },
  { code: '+266', flag: '🇱🇸', name: 'LS', fullName: 'Lesotho' },
  { code: '+231', flag: '🇱🇷', name: 'LR', fullName: 'Liberia' },
  { code: '+218', flag: '🇱🇾', name: 'LY', fullName: 'Libya' },
  { code: '+423', flag: '🇱🇮', name: 'LI', fullName: 'Liechtenstein' },
  { code: '+370', flag: '🇱🇹', name: 'LT', fullName: 'Lithuania' },
  { code: '+352', flag: '🇱🇺', name: 'LU', fullName: 'Luxembourg' },
  { code: '+853', flag: '🇲🇴', name: 'MO', fullName: 'Macao' },
  { code: '+261', flag: '🇲🇬', name: 'MG', fullName: 'Madagascar' },
  { code: '+265', flag: '🇲🇼', name: 'MW', fullName: 'Malawi' },
  { code: '+60', flag: '🇲🇾', name: 'MY', fullName: 'Malaysia' },
  { code: '+960', flag: '🇲🇻', name: 'MV', fullName: 'Maldives' },
  { code: '+223', flag: '🇲🇱', name: 'ML', fullName: 'Mali' },
  { code: '+356', flag: '🇲🇹', name: 'MT', fullName: 'Malta' },
  { code: '+692', flag: '🇲🇭', name: 'MH', fullName: 'Marshall Islands' },
  { code: '+222', flag: '🇲🇷', name: 'MR', fullName: 'Mauritania' },
  { code: '+230', flag: '🇲🇺', name: 'MU', fullName: 'Mauritius' },
  { code: '+52', flag: '🇲🇽', name: 'MX', fullName: 'Mexico' },
  { code: '+691', flag: '🇫🇲', name: 'FM', fullName: 'Micronesia' },
  { code: '+373', flag: '🇲🇩', name: 'MD', fullName: 'Moldova' },
  { code: '+377', flag: '🇲🇨', name: 'MC', fullName: 'Monaco' },
  { code: '+976', flag: '🇲🇳', name: 'MN', fullName: 'Mongolia' },
  { code: '+382', flag: '🇲🇪', name: 'ME', fullName: 'Montenegro' },
  { code: '+212', flag: '🇲🇦', name: 'MA', fullName: 'Morocco' },
  { code: '+258', flag: '🇲🇿', name: 'MZ', fullName: 'Mozambique' },
  { code: '+95', flag: '🇲🇲', name: 'MM', fullName: 'Myanmar' },
  { code: '+264', flag: '🇳🇦', name: 'NA', fullName: 'Namibia' },
  { code: '+674', flag: '🇳🇷', name: 'NR', fullName: 'Nauru' },
  { code: '+977', flag: '🇳🇵', name: 'NP', fullName: 'Nepal' },
  { code: '+31', flag: '🇳🇱', name: 'NL', fullName: 'Netherlands' },
  { code: '+64', flag: '🇳🇿', name: 'NZ', fullName: 'New Zealand' },
  { code: '+505', flag: '🇳🇮', name: 'NI', fullName: 'Nicaragua' },
  { code: '+227', flag: '🇳🇪', name: 'NE', fullName: 'Niger' },
  { code: '+234', flag: '🇳🇬', name: 'NG', fullName: 'Nigeria' },
  { code: '+389', flag: '🇲🇰', name: 'MK', fullName: 'North Macedonia' },
  { code: '+47', flag: '🇳🇴', name: 'NO', fullName: 'Norway' },
  { code: '+968', flag: '🇴🇲', name: 'OM', fullName: 'Oman' },
  { code: '+92', flag: '🇵🇰', name: 'PK', fullName: 'Pakistan' },
  { code: '+680', flag: '🇵🇼', name: 'PW', fullName: 'Palau' },
  { code: '+970', flag: '🇵🇸', name: 'PS', fullName: 'Palestine' },
  { code: '+507', flag: '🇵🇦', name: 'PA', fullName: 'Panama' },
  { code: '+675', flag: '🇵🇬', name: 'PG', fullName: 'Papua New Guinea' },
  { code: '+595', flag: '🇵🇾', name: 'PY', fullName: 'Paraguay' },
  { code: '+51', flag: '🇵🇪', name: 'PE', fullName: 'Peru' },
  { code: '+63', flag: '🇵🇭', name: 'PH', fullName: 'Philippines' },
  { code: '+48', flag: '🇵🇱', name: 'PL', fullName: 'Poland' },
  { code: '+351', flag: '🇵🇹', name: 'PT', fullName: 'Portugal' },
  { code: '+974', flag: '🇶🇦', name: 'QA', fullName: 'Qatar' },
  { code: '+40', flag: '🇷🇴', name: 'RO', fullName: 'Romania' },
  { code: '+7', flag: '🇷🇺', name: 'RU', fullName: 'Russia' },
  { code: '+250', flag: '🇷🇼', name: 'RW', fullName: 'Rwanda' },
  { code: '+1869', flag: '🇰🇳', name: 'KN', fullName: 'Saint Kitts and Nevis' },
  { code: '+1758', flag: '🇱🇨', name: 'LC', fullName: 'Saint Lucia' },
  { code: '+1784', flag: '🇻🇨', name: 'VC', fullName: 'Saint Vincent' },
  { code: '+685', flag: '🇼🇸', name: 'WS', fullName: 'Samoa' },
  { code: '+378', flag: '🇸🇲', name: 'SM', fullName: 'San Marino' },
  { code: '+239', flag: '🇸🇹', name: 'ST', fullName: 'Sao Tome and Principe' },
  { code: '+966', flag: '🇸🇦', name: 'SA', fullName: 'Saudi Arabia' },
  { code: '+221', flag: '🇸🇳', name: 'SN', fullName: 'Senegal' },
  { code: '+381', flag: '🇷🇸', name: 'RS', fullName: 'Serbia' },
  { code: '+248', flag: '🇸🇨', name: 'SC', fullName: 'Seychelles' },
  { code: '+232', flag: '🇸🇱', name: 'SL', fullName: 'Sierra Leone' },
  { code: '+65', flag: '🇸🇬', name: 'SG', fullName: 'Singapore' },
  { code: '+421', flag: '🇸🇰', name: 'SK', fullName: 'Slovakia' },
  { code: '+386', flag: '🇸🇮', name: 'SI', fullName: 'Slovenia' },
  { code: '+677', flag: '🇸🇧', name: 'SB', fullName: 'Solomon Islands' },
  { code: '+252', flag: '🇸🇴', name: 'SO', fullName: 'Somalia' },
  { code: '+27', flag: '🇿🇦', name: 'ZA', fullName: 'South Africa' },
  { code: '+82', flag: '🇰🇷', name: 'KR', fullName: 'South Korea' },
  { code: '+211', flag: '🇸🇸', name: 'SS', fullName: 'South Sudan' },
  { code: '+34', flag: '🇪🇸', name: 'ES', fullName: 'Spain' },
  { code: '+94', flag: '🇱🇰', name: 'LK', fullName: 'Sri Lanka' },
  { code: '+249', flag: '🇸🇩', name: 'SD', fullName: 'Sudan' },
  { code: '+597', flag: '🇸🇷', name: 'SR', fullName: 'Suriname' },
  { code: '+46', flag: '🇸🇪', name: 'SE', fullName: 'Sweden' },
  { code: '+41', flag: '🇨🇭', name: 'CH', fullName: 'Switzerland' },
  { code: '+963', flag: '🇸🇾', name: 'SY', fullName: 'Syria' },
  { code: '+886', flag: '🇹🇼', name: 'TW', fullName: 'Taiwan' },
  { code: '+992', flag: '🇹🇯', name: 'TJ', fullName: 'Tajikistan' },
  { code: '+255', flag: '🇹🇿', name: 'TZ', fullName: 'Tanzania' },
  { code: '+66', flag: '🇹🇭', name: 'TH', fullName: 'Thailand' },
  { code: '+670', flag: '🇹🇱', name: 'TL', fullName: 'Timor-Leste' },
  { code: '+228', flag: '🇹🇬', name: 'TG', fullName: 'Togo' },
  { code: '+676', flag: '🇹🇴', name: 'TO', fullName: 'Tonga' },
  { code: '+1868', flag: '🇹🇹', name: 'TT', fullName: 'Trinidad and Tobago' },
  { code: '+216', flag: '🇹🇳', name: 'TN', fullName: 'Tunisia' },
  { code: '+90', flag: '🇹🇷', name: 'TR', fullName: 'Turkey' },
  { code: '+993', flag: '🇹🇲', name: 'TM', fullName: 'Turkmenistan' },
  { code: '+688', flag: '🇹🇻', name: 'TV', fullName: 'Tuvalu' },
  { code: '+256', flag: '🇺🇬', name: 'UG', fullName: 'Uganda' },
  { code: '+380', flag: '🇺🇦', name: 'UA', fullName: 'Ukraine' },
  { code: '+971', flag: '🇦🇪', name: 'AE', fullName: 'United Arab Emirates' },
  { code: '+44', flag: '🇬🇧', name: 'GB', fullName: 'United Kingdom' },
  { code: '+1', flag: '🇺🇸', name: 'US', fullName: 'United States' },
  { code: '+598', flag: '🇺🇾', name: 'UY', fullName: 'Uruguay' },
  { code: '+998', flag: '🇺🇿', name: 'UZ', fullName: 'Uzbekistan' },
  { code: '+678', flag: '🇻🇺', name: 'VU', fullName: 'Vanuatu' },
  { code: '+379', flag: '🇻🇦', name: 'VA', fullName: 'Vatican City' },
  { code: '+58', flag: '🇻🇪', name: 'VE', fullName: 'Venezuela' },
  { code: '+84', flag: '🇻🇳', name: 'VN', fullName: 'Vietnam' },
  { code: '+967', flag: '🇾🇪', name: 'YE', fullName: 'Yemen' },
  { code: '+260', flag: '🇿🇲', name: 'ZM', fullName: 'Zambia' },
  { code: '+263', flag: '🇿🇼', name: 'ZW', fullName: 'Zimbabwe' },
] as const;

export const YACHT_TYPES = [
  { value: 'sailing', label: 'Sailing Yacht' },
  { value: 'catamaran', label: 'Catamaran' },
  { value: 'cabin', label: 'Cabin Cruise' },
  { value: 'bareboat', label: 'Bareboat Charter' },
  { value: 'crewed-day-charter', label: 'Crewed Day Charter' },
  { value: 'crewed-overnight-charter', label: 'Crewed Overnight Charter' },
  { value: 'unsure', label: 'Not sure' },
] as const;

export const TRIP_TYPES = [
  { value: 'family', label: 'Family' },
  { value: 'romantic', label: 'Romantic' },
  { value: 'adventure', label: 'Adventure' },
  { value: 'corporate', label: 'Corporate' },
  { value: 'celebration', label: 'Special Occasion' },
] as const;

export const COMMUNICATION_CHANNELS = [
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'whatsapp', label: 'WhatsApp' },
  { value: 'line', label: 'Line' },
] as const;

export type CountryCode = typeof COUNTRY_CODES[number]['code'];
export type YachtType = typeof YACHT_TYPES[number]['value'];
export type TripType = typeof TRIP_TYPES[number]['value'];
export type CommunicationChannel = typeof COMMUNICATION_CHANNELS[number]['value'];
